### ISSUE TITLE
Documentation for using the codebase

### ISSUE THREAD

**Issue by HashmatShadab** [jiamingzhang94/Adversarial-Prompt-Tuning#4]
Hi! Thanks for sharing your work.

I would request the authors to update the Readme file of the project to document how to run experiments for training and evaluation. Better documentation would significantly help in using the codebase.

**Comment by jiamingzhang94** [comment]
Thank you for your interest in our work and for your feedback!

We’ve updated the README file to include instructions on running experiments for training and evaluation. We hope this makes it easier for you to use the codebase. If you have any further questions or suggestions, please feel free to reach out!
