### ISSUE TITLE
Cannot find the runners package

### ISSUE THREAD

**Issue by HashmatShadab** [jiamingzhang94/Adversarial-Prompt-Tuning#7]
https://github.com/jiamingzhang94/Adversarial-Prompt-Tuning/blob/a6ada7e666efc67a110ba5d5b3779570cd6ded6c/attack/purification.py#L13-L17

**Comment by jiamingzhang94** [comment]
You can comment out the code involving 'runners' or download the updated code. See #2

**Comment by HashmatShadab** [comment]
The updated code doesn't have the purification methods from the runners package. Can you please provide instructions to add them so that the results mentioned in your paper can be reproduced?
